name: CI Pipeline

on:
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_dispatch: # manual trigger

jobs:
    prepare-code:
        name: Prepare Code
        runs-on: ubuntu-latest
        container:
            image: pp-maven:3.9.5-openjdk-17
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Make prepare-code.sh executable
              run: chmod +x ./prepare-code.sh

            - name: Run prepare-code.sh
              run: ./prepare-code.sh

    build_package:
        name: Build Package
        if: github.event_name == 'pull_request' && github.base_ref != 'master' && github.base_ref != 'develop'
        runs-on: ubuntu-latest
        container:
            image: pp-maven:3.9.5-openjdk-17
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Maven clean install
              run: mvn clean install -U

        # Manual trigger support
        permissions:
            contents: read

    build_sanity:
        name: Build Sanity
        runs-on: ubuntu-latest
        container:
            image: pp-maven:3.9.5-openjdk-17
        needs: [prepare-code]
        if: github.base_ref != 'master' && github.base_ref != 'stage' && github.base_ref != 'develop'
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Maven verify with quality check profile
              env:
                  SONAR_PULLREQUEST_KEY: ${{ github.event.pull_request.number }}
                  SONAR_PULLREQUEST_BRANCH: ${{ github.head_ref }}
                  SONAR_PULLREQUEST_BASE: ${{ github.base_ref }}
              run: mvn clean verify -U -Pquality_check -Dsonar.pullrequest.key=${{ env.SONAR_PULLREQUEST_KEY }} -Dsonar.pullrequest.branch=${{ env.SONAR_PULLREQUEST_BRANCH }} -Dsonar.pullrequest.base=${{ env.SONAR_PULLREQUEST_BASE }}

            - name: Upload test reports
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: junit-reports
                  path: target/surefire-reports/TEST-*.xml
