name: Publish package to the Maven Central Repository
on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup central
              uses: actions/setup-java@v4
              with:
                  java-version: 8
                  cache: maven
                  distribution: 'temurin'
                  server-username: ${{secrets.MAVEN_USERNAME}}
                  server-password: ${{secrets.MAVEN_PASSWORD}}
                  gpg-private-key: ${{ secrets.CENTRAL_GPG_KEY }}
                  gpg-passphrase:  ${{ secrets.MAVEN_GPG_PASSPHRASE }}
            - name: Publish package
              run: mvn --batch-mode deploy -Pcentral-release
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
                  MAVEN_GPG_PASSPHRASE: ${{ secrets.CENTRAL_GPG_KEY_PASSWORD }}